### ISSUE TITLE
Code improvement to get the ASUS Router Model ID

### ISSUE THREAD

**Issue by Martinski4GitHub** [Firetop/MerlinAutoUpdate-Router#1]
Here's an improvement in the "**MerlinAutoUpdate.sh**" shell script for getting the router model ID.  Instead of the current syntax:

`MODEL=$(nvram get model)`

Use the following function:

##################################################
**GetRouterModel()
{
	local retCode=1  routerModelID="N/A"
	local nvramModelKeys="odmpid productid wps_modelnum wps_device_name model"
	for nvramKey in $nvramModelKeys
	do
		routerModelID="$(nvram get "$nvramKey")"
		[ -n "$routerModelID" ] && retCode=0 && break
	done
	echo "$routerModelID" ; return "$retCode"
}**
##################################################

_EXAMPLE USAGE:_

**if ! MODEL="$(GetRouterModel)"
then echo "**ERROR**: UNKNOWN Router Model" ; exit 1 ; fi**

The reason is that not all ASUS routers use or set the "**model**" NVRAM variable; most use either "**odmpid**" or "**productid**" variable to store the router model ID. Other keys in the list could be used as well.

**Comment by Firetop** [comment]
Merged!

Thank you for your help and contribution!

**Comment by dave14305** [comment]
Just FYI that RMerlin only relies on productid when checking for updates.

https://github.com/RMerl/asuswrt-merlin.ng/blob/7f513adff207ce8efe156a7aecc39359e28ec264/release/src/router/rom/webs_scripts/merlin_webs_update.sh#L25C29-L25C29

**Comment by Martinski4GitHub** [comment]
I don't know when the F/W had the "**odmpid**" NVRAM variable set. I suspect that it was used in older AC class routers or perhaps older F/W branches. In any case, the function is set up to go through the NVRAM keys until it finds a non-empty value. Chances are 99.999% that the model ID will be obtained within the 1st two tries. You can swap the key names if you want so that "**productid**" is found before the "**odmpid**" key name. No harm is done either way.

**Comment by Martinski4GitHub** [comment]
I fixed the function to get the router model ID. @dave14305 was correct that when checking for firmware updates, we need to get the value that matches the "Base Product ID" (e.g. "RT-AX86U") instead of the specific "Model ID" (e.g. "RT-AX86S").
