### ISSUE TITLE
Get username from nvram

### ISSUE THREAD

**Issue by dave14305** [Firetop/MerlinAutoUpdate-Router#10]
https://github.com/Firetop/MerlinAutoUpdate-Router/blob/21465c81c2f4f18797e7ffd158a8c6a2949fbb96/MerlinAutoUpdate.sh#L211

We can get the username from http_username directly instead of an extra prompt to the user.

**Comment by Firetop** [comment]
Resolved in latest commit:

https://github.com/Firetop/MerlinAutoUpdate-Router/commit/58476a255c0d738e917440abe8129945be5c51cf
