### ISSUE TITLE
Code improvement to get the Router F/W Version

### ISSUE THREAD

**Issue by Martinski4GitHub** [Firetop/MerlinAutoUpdate-Router#2]
Another improvement in the "**MerlinAutoUpdate.sh**" shell script for getting the current F/W version.  Instead of the current syntax:

`current_version=$(nvram get buildno)`

Use the following syntax:

`current_version="$(nvram get buildno)_$(nvram get extendno)"`

The new syntax gives the **full** F/W version string (e.g. "**388.2_4**") while the current syntax gives only a **partial** version (e.g. "**388.2**").

**Comment by Firetop** [comment]
Merged as requested. Thank you for your help and contribution!

**Comment by Firetop** [comment]
Idk why it didn't actually merge so I made the change myself lol.
