### ISSUE TITLE
Account for https or custom ports

### ISSUE THREAD

**Issue by dave14305** [Firetop/MerlinAutoUpdate-Router#8]
A user may have https-only configured, or use a custom port for either http or https. Fetch the protocol and port from nvram to construct the url.

You can refer to this function from FlexQoS to see the method used.

https://github.com/dave14305/FlexQoS/blob/2c969cb3aa8fc8a6d5d1167c3e073c3d8d8b9f41/flexqos.sh#L528-L554

**Comment by Firetop** [comment]
Resolved in the latest commit.

https://github.com/Firetop/MerlinAutoUpdate-Router/commit/b8d9d7ffa6d4f9cce85c9fa9ae997001600a9a85

Thanks for your feedback as always dave, great insight on how these routers are configured.
